### ISSUE TITLE
Add example triads of SpelledPitch values to demonstrate rule generation

### ISSUE THREAD

**Issue by jsbean** [jsbean/PitchSpelling#3]

**Comment by mossheim** [comment]
I'm going to try out two triads in very different realms of the problem space: {0, 1, 2} and {0.25, 5.75, 7.75}. since the number of possible combinations is quite large (up to 6^3), i'll be using a lot of shorthand. not really sure how it'll look until i have it down on paper!

probably the next ones to do after that would be ones that mix resolutions, like {0, 0.25, 0.5}.

**Comment by jsbean** [comment]
Oh please do :). Maybe just for a running start, do something like {0,2,4} or {2,5,7}.

**Comment by mossheim** [comment]
Hey, look at issue #6 . Whether or not you agree, I'm going to to the second triad chart by drawing it the way it would work in the program, with some branches being left unexplored. I'll scan and upload when done!

**Comment by mossheim** [comment]
I added a PDF with an example for {0,1,2} (p.4) and also an example of the way the exploration procedure would operate for {0.25, 5.75, 7.75}. There was a mistake I made in assigning costs, and of course the whole thing operates under the assumption that all costs are scaled at 1, but it worked out pretty well in finding correct spellings! And in about 50 (arbitrarily distinct) steps. I'm going to do another more rigorous one for {2,5.25,8.25}.
